FROM ubuntu:20.04
LABEL maintainer="Mario Cho <hephaex@gmail.com>"

RUN apt-get update && \
    apt-get install -y \
        python3 \
        python3-pip \
        bash \
        curl
RUN curl -sSL https://get.docker.com/ | sh
RUN pip3 install --upgrade \
        pip \
        setuptools \
        pyyaml \
        absl-py \
        cerberus \
        docker

WORKDIR /work
VOLUME ["/work"]

COPY bash.bashrc /etc/bash.bashrc
RUN chmod a+rwx /etc/bash.bashrc
