"function toggleVisibility(linkObj)\n"
"{\n"
" var base = $(linkObj).attr('id');\n"
" var summary = $('#'+base+'-summary');\n"
" var content = $('#'+base+'-content');\n"
" var trigger = $('#'+base+'-trigger');\n"
" var src=$(trigger).attr('src');\n"
" if (content.is(':visible')===true) {\n"
"   content.hide();\n"
"   summary.show();\n"
"   $(linkObj).addClass('closed').removeClass('opened');\n"
"   $(trigger).attr('src',src.substring(0,src.length-8)+'closed.png');\n"
" } else {\n"
"   content.show();\n"
"   summary.hide();\n"
"   $(linkObj).removeClass('closed').addClass('opened');\n"
"   $(trigger).attr('src',src.substring(0,src.length-10)+'open.png');\n"
" } \n"
" return false;\n"
"}\n"
"\n"
"function updateStripes()\n"
"{\n"
"  $('table.directory tr').\n"
"       removeClass('even').filter(':visible:even').addClass('even');\n"
"}\n"
"\n"
"function toggleLevel(level)\n"
"{\n"
"  $('table.directory tr').each(function() {\n"
"    var l = this.id.split('_').length-1;\n"
"    var i = $('#img'+this.id.substring(3));\n"
"    var a = $('#arr'+this.id.substring(3));\n"
"    if (l<level+1) {\n"
"      i.removeClass('iconfopen iconfclosed').addClass('iconfopen');\n"
"      a.html('&#9660;');\n"
"      $(this).show();\n"
"    } else if (l==level+1) {\n"
"      i.removeClass('iconfclosed iconfopen').addClass('iconfclosed');\n"
"      a.html('&#9658;');\n"
"      $(this).show();\n"
"    } else {\n"
"      $(this).hide();\n"
"    }\n"
"  });\n"
"  updateStripes();\n"
"}\n"
"\n"
"function toggleFolder(id)\n"
"{\n"
"  // the clicked row\n"
"  var currentRow = $('#row_'+id);\n"
"\n"
"  // all rows after the clicked row\n"
"  var rows = currentRow.nextAll(\"tr\");\n"
"\n"
"  var re = new RegExp('^row_'+id+'\\\\d+_$', \"i\"); //only one sub\n"
"\n"
"  // only match elements AFTER this one (can't hide elements before)\n"
"  var childRows = rows.filter(function() { return this.id.match(re); });\n"
"\n"
"  // first row is visible we are HIDING\n"
"  if (childRows.filter(':first').is(':visible')===true) {\n"
"    // replace down arrow by right arrow for current row\n"
"    var currentRowSpans = currentRow.find(\"span\");\n"
"    currentRowSpans.filter(\".iconfopen\").removeClass(\"iconfopen\").addClass(\"iconfclosed\");\n"
"    currentRowSpans.filter(\".arrow\").html('&#9658;');\n"
"    rows.filter(\"[id^=row_\"+id+\"]\").hide(); // hide all children\n"
"  } else { // we are SHOWING\n"
"    // replace right arrow by down arrow for current row\n"
"    var currentRowSpans = currentRow.find(\"span\");\n"
"    currentRowSpans.filter(\".iconfclosed\").removeClass(\"iconfclosed\").addClass(\"iconfopen\");\n"
"    currentRowSpans.filter(\".arrow\").html('&#9660;');\n"
"    // replace down arrows by right arrows for child rows\n"
"    var childRowsSpans = childRows.find(\"span\");\n"
"    childRowsSpans.filter(\".iconfopen\").removeClass(\"iconfopen\").addClass(\"iconfclosed\");\n"
"    childRowsSpans.filter(\".arrow\").html('&#9658;');\n"
"    childRows.show(); //show all children\n"
"  }\n"
"  updateStripes();\n"
"}\n"
"\n"
"\n"
"function toggleInherit(id)\n"
"{\n"
"  var rows = $('tr.inherit.'+id);\n"
"  var img = $('tr.inherit_header.'+id+' img');\n"
"  var src = $(img).attr('src');\n"
"  if (rows.filter(':first').is(':visible')===true) {\n"
"    rows.css('display','none');\n"
"    $(img).attr('src',src.substring(0,src.length-8)+'closed.png');\n"
"  } else {\n"
"    rows.css('display','table-row'); // using show() causes jump in firefox\n"
"    $(img).attr('src',src.substring(0,src.length-10)+'open.png');\n"
"  }\n"
"}\n"
"\n"
